### ISSUE TITLE
Add Storybook

### ISSUE THREAD

**Issue by rafaelbcerri** [Laboratoria/ui#50]
Hey!!

What do you think about add [Storybook](https://storybook.js.org/) to this project? 

Since we doesn't have a lot of components yet, it will be easier and faster to add it now. And it will help us to build and document other components faster 🚀 

**What is Storybook?** 
Storybook is a development environment for UI components. It allows you to browse a component library, view the different states of each component, and interactively develop and test components

**How can I install it?**
Guide to install [Storybook for React](https://storybook.js.org/docs/basics/guide-react/)

**Comment by gmoura** [comment]
Nice @rafaelbcerri, I totally agree with you, Storybook it's a nice way to doc React Components.  I'd love to see Storybook in this project ❤️

![](https://media.giphy.com/media/qDPg6HNz2NfAk/giphy.gif)

**Comment by MaiaRojas** [comment]
I had heard about storybook in a meetup I have not been able to use it, it would be good if we included :rocket:

**Comment by AnaSalazar** [comment]
I love this idea

![](https://media.giphy.com/media/xT0xemaMYnb6pobtXW/giphy.gif)

**Comment by rafaelbcerri** [comment]
Awesome 😃 

And what do you think about the tests? Since these components are going to be used on all applications, they should have some tests. On the [documentation](https://storybook.js.org/docs/testing/react-ui-testing/) they talk about three kinds of automated tests,  should we do all, one, none? hahaha
