### ISSUE TITLE
Create Alert component

### ISSUE THREAD

**Issue by rafaelbcerri** [Laboratoria/ui#61]
### `text`
This property must contain the text that will appear in the alert

### `closeTime`
This property can contain the time that will auto close the alert

### `onClose`
This property can contain the function that will happen when to alert is closed

## Layout

[**Layout on Figma**](https://www.figma.com/file/09a5R3KepA4ghHS6TWqTly/Laboratoria-Style-Guide?node-id=1061%3A253)

![Screen Shot 2019-04-26 at 13 56 54](https://user-images.githubusercontent.com/11894994/56823773-32ff8600-682b-11e9-930e-015f17128922.png)

![Screen Shot 2019-04-26 at 13 56 57](https://user-images.githubusercontent.com/11894994/56823772-32ff8600-682b-11e9-8aac-d3984bcccd06.png)

**Comment by gmoura** [comment]
Gracias @AnaSalazar
