### ISSUE TITLE
Create Input component

### ISSUE THREAD

**Issue by rafaelbcerri** [Laboratoria/ui#62]
### `label`
This property is required and receive a string.

### `placeholder`
This property is not required and receive a string.

### `type`
This property is not required and receive a string with one of HTML5 input type.

### `value`
This property is required and receive a string.

### `onChange(event)`
This property is require and receive a function that will be called on the input change and send the event as parameter.

## Layout

[**Layout on Figma**](https://www.figma.com/file/09a5R3KepA4ghHS6TWqTly/Laboratoria-Style-Guide?node-id=491%3A192)

![Screen Shot 2019-05-13 at 12 46 55](https://user-images.githubusercontent.com/11894994/57635355-5b061d80-757d-11e9-8569-65de5fe44d8f.png)

**Comment by gmoura** [comment]
Done http://ui.laboratoria.la/?path=/story/inputs--textfield
